services:

  www:
    depends_on:
      - campus_db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./data:/var/www/data
    ports:
      - 80:80
      - 443:443
    networks:
      - network

  campus_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: campus_map
      MYSQL_USER: webuser
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./databases/campus-map:/docker-entrypoint-initdb.d
    networks:
      - network

  community_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: community_map
      MYSQL_USER: webuser
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./databases/community-map:/docker-entrypoint-initdb.d
    networks:
      - network

  phpmyadmin:
    depends_on:
      - campus_db
      - community_db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=community_db
      - PMA_PORT=3306
    networks:
      - network

networks:
  network:
    driver: bridge